name: Deploy Application

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement applicatif via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            cd /opt/appclasses-LSCDK

            # 1. Récupérer le dernier code de l'app
            git pull origin prod

            # 2. Reconstruire et relancer l'API et Mongo
            docker compose build api
            docker compose up -d api mongo

            # 3. Mettre à jour Prisma dans le conteneur et exécuter le Seed
            docker compose exec -T api npx prisma db push
