name: Deploy Production

on:
  push:
    branches:
      - prod # Déclenche le déploiement uniquement lors d'un push sur 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            cd /opt/myapp
            
            # 1. Récupérer la mise à jour du code
            git pull origin prod
            
            # 2. Reconstruire le conteneur PHP si vous avez modifié le Dockerfile ou des dépendances
            sudo docker compose build php
            
            # 3. Relancer l'application sans coupure pour le reste du serveur
            sudo docker compose up -d php
